# This is a basic workflow to help you get started with Actions

name: trufflehog

env:
  GH_TOKEN: ${{ github.token }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install truffleHog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Trufflehog Repo variables
          OWNER=trufflesecurity
          REPO=trufflehog
          
          echo === Get latest trufflehog release ASSET_ID and ASSET_NAME from GitHub ===
          export $(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/trufflesecurity/trufflehog/releases/latest \
            | jq -r '.assets [] | select(.name | contains("linux_amd64")) | @sh "ASSET_ID=\(.id) ASSET_NAME=\(.name)"')
          
          echo === Download release asset ===
          gh api \
            -H "Accept: application/octet-stream" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$OWNER/$REPO/releases/assets/$ASSET_ID > $GITHUB_WORKSPACE/$ASSET_NAME

          echo ===  Extract release archive ===
          tar xf $ASSET_NAME
          
          echo === Make exexutable ===
          chmod +x ./trufflehog

      - name: Run truffleHog with GitHub output (i.e. decorate the Pull Request)
        run: |
          ./trufflehog git file://$GITHUB_WORKSPACE \
          --since-commit ${{ github.event.repository.default_branch }} \
          --branch HEAD \
          --fail \
          --no-update \
          --debug \
          --only-verified \
          --github-actions
          
      - name: Run truffleHog with JSON output
        run: |
          ./trufflehog git file://$GITHUB_WORKSPACE \
          --since-commit ${{ github.event.repository.default_branch }} \
          --branch HEAD \
          --fail \
          --no-update \
          --debug \
          --only-verified \
          --json >> trufflehog-output.json

      - name: Install awscli tools
        run: |
          sudo apt -y install awscli coreutils

      - name: Upload Trufflehog output to S3
        run: |
          AWS_BUCKET_NAME=trufflehog-github-action-test
          PATH=$(date +%Y/%m/%d)
          SOURCE_FILENAME=trufflehog-output.json
          DEST_FILENAME=$(date --iso-8601=seconds)-$SOURCE_FILENAME
          AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws s3 cp $SOURCE_FILENAME s3://$AWS_BUCKET_NAME/$PATH/$DEST_FILENAME
          
