name: trufflehog

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install truffleHog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Trufflehog Repo variables
          OWNER=trufflesecurity
          REPO=trufflehog
          
          echo === Get latest trufflehog release ASSET_ID and ASSET_NAME from GitHub ===
          export $(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/trufflesecurity/trufflehog/releases/latest \
            | jq -r '.assets [] | select(.name | contains("linux_amd64")) | @sh "ASSET_ID=\(.id) ASSET_NAME=\(.name)"')
          
          echo === Download release asset ===
          gh api \
            -H "Accept: application/octet-stream" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$OWNER/$REPO/releases/assets/$ASSET_ID > $GITHUB_WORKSPACE/$ASSET_NAME

          echo ===  Extract release archive ===
          tar xf $ASSET_NAME
          
          echo === Make exexutable ===
          chmod +x ./trufflehog

      - name: Run truffleHog with GitHub output (i.e. decorate the Pull Request)
        run: |
          echo === Run trufflehog ===
          ./trufflehog git file://$GITHUB_WORKSPACE \
          --since-commit ${{ github.event.repository.default_branch }} \
          --branch HEAD \
          --fail \
          --no-update \
          --debug \
          --only-verified \
          --github-actions
          
      - name: Run truffleHog with JSON output
        run: |
          echo === Run trufflehog ===
          ./trufflehog git file://$GITHUB_WORKSPACE \
          --since-commit ${{ github.event.repository.default_branch }} \
          --branch HEAD \
          --fail \
          --no-update \
          --only-verified \
          --json 2>&1 | tee trufflehog-output.json

      - name: Install awscli tools
        run: |
          echo === Install awscli ===
          sudo apt -y install awscli

      - name: Upload Trufflehog output to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TRUFFLEHOG_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TRUFFLEHOG_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          BUCKET_NAME=trufflehog-github-action-test
          PATH=$(/bin/date +%Y/%m/%d)
          SOURCE_FILENAME=trufflehog-output.json
          DEST_FILENAME=$(/bin/date --iso-8601=seconds)-$SOURCE_FILENAME

          echo === Upload to S3 ===
          /usr/bin/aws s3 cp $SOURCE_FILENAME s3://$BUCKET_NAME/$PATH/$DEST_FILENAME
          
